server:
  port: 2022

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/medochemie
      auto-index-creation: true
  application:
    name: MC-AGENT-SERVICE
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost